name: Dev Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: 35.91.158.236 # Замените на IP-адрес или хост-имя вашей EC2-инстанции
          username: ubuntu # Замените на имя пользователя для доступа к EC2-инстанции
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Замените на значение приватного ключа SSH, сохраненного в secrets вашего репозитория
          source: ./
          target: /home/ubuntu/ # Замените на путь к месту назначения на EC2-инстанции

      - name: Connect to EC2 and deploy
        run: |
          echo "$secrets.SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -i private_key ubuntu@35.91.158.236 '
            sudo apt update
            sudo apt install git curl
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            sudo usermod -aG docker $USER
            git clone --depth 1 https://github.com/brocoders/nestjs-boilerplate.git my-app
            cd my-app/
            cp env-example .env
            sudo docker compose up -d
          '
