name: Dev Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: 34.220.80.221 # Замените на IP-адрес или хост-имя вашей EC2-инстанции
          username: ubuntu # Замените на имя пользователя для доступа к EC2-инстанции
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Замените на значение приватного ключа SSH, сохраненного в secrets вашего репозитория
          source: ./
          target: /home/ubuntu/ # Замените на путь к месту назначения на EC2-инстанции

      - name: Connect to EC2 and deploy
        run: |
          ssh -i <SSH_PRIVATE_KEY> <EC2_USERNAME>@<EC2_HOST> "cd /home/ubuntu/ && echo "Hello""
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Замените на путь к приватному ключу SSH на вашей локальной машине
          EC2_USERNAME: ubuntu # Замените на имя пользователя для доступа к EC2-инстанции
          EC2_HOST: 34.220.80.221 # Замените на IP-адрес или хост-имя вашей EC2-инстанции
