name: Dev Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/vm.key
          chmod 600 ~/.ssh/vm.key
          cat >>~/.ssh/config <<END
          Host vm
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/vm.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.MY_SSH_USER }}
          SSH_KEY: ${{ secrets.MY_SSH_KEY }}
          SSH_HOST: ${{ secrets.MY_SSH_HOST }}

      - name: Deploy to EC2 remote server
        run: |
          ssh vm 'sudo apt update && sudo apt install git curl -y'
          ssh vm 'git clone https://github.com/unk42/backend.git'
          ssh vm 'cd backend'
          ssh vm 'cp env-example .env'
          ssh vm 'sudo docker compose up -d'
          ssh vm 'echo "PASS!!"'
          
