name: Dev Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: 54.185.172.27 # Замените на IP-адрес или хост-имя вашей EC2-инстанции
          username: ubuntu # Замените на имя пользователя для доступа к EC2-инстанции
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Замените на значение приватного ключа SSH, сохраненного в secrets вашего репозитория
          source: ./
          target: /home/ubuntu/ # Замените на путь к месту назначения на EC2-инстанции
          run: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H your_ec2_instance_ip >> ~/.ssh/known_hosts
            ssh -i ~/.ssh/id_rsa ubuntu@54.185.172.27 '
              sudo apt update
              sudo apt install git curl
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              sudo usermod -aG docker ubuntu
              git clone --depth 1 https://github.com/brocoders/nestjs-boilerplate.git my-app
              cd my-app/
              cp env-example .env
              sudo docker compose up -d
            '
