name: Dev Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to EC2
        with:
          host: 54.185.172.27 # Замените на IP-адрес или хост-имя вашей EC2-инстанции
          username: ubuntu # Замените на имя пользователя для доступа к EC2-инстанции
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Замените на значение приватного ключа SSH, сохраненного в secrets вашего репозитория
          source: ./
          target: /home/ubuntu/ # Замените на путь к месту назначения на EC2-инстанции
          run: |
            echo "heee!"
            echo "hiiiii!"
            echo "dedede"
